name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproducing
    attributes:
      label: Instructions to Reproduce the Bug
      description: What were the steps you ran that resulted in the bug? Include code snippets if possible.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Traceback
      description: If an error or exception was raised include the full traceback.
      render: shell
    validations:
      required: false
