name: Build Documentation

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ."[dev]"
      - name: Make documentation
        run: |
          cd docs
          make html
          cd ..
      - name: Push changes to working branch
        run: |
          git remote set-url --push origin
          git remote set-url --add origin
          git status
          git add -f docs/*
          git commit -m "auto updating docs"
          git push
